---
apiVersion: v1
kind: Pod
metadata:
  name: multinginx
spec:
  containers:
    - name: multinginxserver
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Always

    - name: multimongoserver
      image: mongo
      ports:
        - containerPort: 7501
      imagePullPolicy: Always