apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx2
        tier: Frontend
    spec:
      containers:
      - name: nginx2
        image: nginx
        ports:
          - containerPort: 80
