---
apiVersion: v1
kind: Pod
metadata:
  name: hostportnginx
spec:
  containers:
    - name: hostportnginx1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8090
      imagePullPolicy: Always